name: cnn-env
channels:
  - defaults
dependencies:
  - python=3.10.13
  - pip
  - pip:
      - boto3
      - docker==7.1.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - joblib==1.4.2
      - jsonpickle==4.0.1
      - matplotlib==3.9.0
      - mlflow==2.18.0
      - mlflow-skinny==2.18.0
      - pytorch-lightning==2.5.0.post0
      - s3transfer==0.10.4
      - scikit-learn==1.6.0
      - sqlalchemy==2.0.36
      - torch
      - torchvision
      - torchaudio
      - graphviz
      - torchview